Added sample notebooks for Rekognition APIs
aws-samples/amazon-rekognition-code-samples pull request #1
Opened 2021-06-08 21:45 UTC by jayrao

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-06-23 11:20 UTC, ConnorKirk commented on rekognition-apis/2-content-moderation.ipynb
> +    "# Curent AWS Region. Use this to choose corresponding S3 bucket with sample content\n",
```suggestion
    "# Current AWS Region. Use this to choose corresponding S3 bucket with sample content\n",
```

2021-06-23 11:33 UTC, ConnorKirk commented on rekognition-apis/4-custom-celebrity-recognition.ipynb
> +    "#cids = listCollectionsResponse[\"CollectionIds\"]\n",
This entire block is commented out. It might be more clear to either remove it, add a paragraph/comment to explain when a user might wish to run it

2021-06-23 11:36 UTC, ConnorKirk requested changes
Thanks for making this contribution Jay. I've made a few suggestions. Overall it looks good

2021-06-23 11:46 UTC, matteofigus reviewed
A couple of suggestions

2021-06-23 11:46 UTC, matteofigus commented on rekognition-apis/2-content-moderation.ipynb
> +    "bucketName = \"aws-rek-immersionday-\" + awsRegion"
This is probably ok to start with in this PR, but maybe we should move to how we did it in the virtual proctoring folder, having a step 0 to create a supporting bucket to make the notebooks to run in all regions and remove dependencies from other buckets? I think the advantage is that if you wanna start playing around, by owning the bucket you can see its content, you can change it, you can learn better

2021-06-23 11:46 UTC, matteofigus commented on rekognition-apis/4-custom-celebrity-recognition.ipynb
> +    "    }\n",
I propose we switch to on-demand to save money
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/dynamodb.html#DynamoDB.Client.create_table

```suggestion
    "    BillingMode='PAY_PER_REQUEST'\n",
```

2021-06-24 19:47 UTC, jayrao commented
Committed the changes requested. Please go ahead with the merge.

2021-06-25 16:28 UTC, ConnorKirk approved these changes

2021-06-25 16:29 UTC, merged