Adding module 5 for identity Verification
aws-samples/amazon-rekognition-code-samples pull request #20
Opened 2022-11-22 22:22 UTC by mzraghib

*Issue #, if available:* N/A

*Description of changes:* Added a notebook in module 5 in the identity verification section and updated the README to include the title for module 5

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-11-23 13:11 UTC, matteofigus requested changes
A couple of changes. Thanks for your help.

2022-11-23 13:11 UTC, matteofigus commented on identity-verification/module_5/Metrics_for_Evaluating_an_Identity_Verification_Solution.ipynb
> +    "This notebook provides a walkthrough of the steps mentioned in the blog \"Metrics for Evaluating an Identity Verification Solution\""
Are you able to link the blogpost here?

2022-11-23 13:11 UTC, matteofigus commented on identity-verification/README.md
> +- Module 4:
```suggestion
- Module 4: Identify Verification Solution
```

Maybe we should provide a description for module 4, which we forgot to do when we added the solution.

2022-11-23 13:11 UTC, matteofigus commented on identity-verification/module_5/Metrics_for_Evaluating_an_Identity_Verification_Solution.ipynb
> +    "import pandas as pd\n",
Consistently with other modules, can you please include a step to install relevant libraries.

2022-11-23 13:11 UTC, matteofigus commented on identity-verification/module_5/Metrics_for_Evaluating_an_Identity_Verification_Solution.ipynb
> +    "SimilarityThresholds = [80,85,90,95,96,97,98,99]\n",
can you keep the python code consistent, using snake_case rather than PascalCase.

2022-11-23 13:11 UTC, matteofigus commented on identity-verification/module_5/Metrics_for_Evaluating_an_Identity_Verification_Solution.ipynb
> +    "# create columnds for y_actual and y_pred\n",
```suggestion
    "# create columns for y_actual and y_pred\n",
```

2022-11-23 14:39 UTC, mzraghib commented on identity-verification/module_5/Metrics_for_Evaluating_an_Identity_Verification_Solution.ipynb
> +    "This notebook provides a walkthrough of the steps mentioned in the blog \"Metrics for Evaluating an Identity Verification Solution\""
Bit of a catch 22 here as the blogpost is not posted yet (which needs the link to this notebook). I will update with the link once it is posted

2022-11-23 23:55 UTC, closed without merging

2022-11-24 11:30 UTC, matteofigus commented on identity-verification/module_5/Metrics_for_Evaluating_an_Identity_Verification_Solution.ipynb
> +    "This notebook provides a walkthrough of the steps mentioned in the blog \"Metrics for Evaluating an Identity Verification Solution\""
I think we can do this later then. Resolving this comment.