Updated ID
aws-samples/amazon-rekognition-code-samples pull request #27
Opened 2023-08-04 14:28 UTC by DanyStinson

*Issue #, if available:*

*Description of changes:*
We have updated the Immersion Day removing some old notebooks and adding new content. 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-08-07 14:04 UTC, matteofigus requested changes
I added some small comments for some improvements. Also, In your PR you are adding a new 3.2 but not removing the old 3.2. Can you add that to the PR, otherwise we'll end up with two 3.2 modules.

2023-08-07 14:04 UTC, matteofigus commented on identity-verification/module_3/3.2 Improving accuracy using user vectors.ipynb
> +  "availableInstances": [
I don't think we need this portion in the metadata - can you check the other labs in the folder and keep this consistent?

2023-08-07 14:04 UTC, matteofigus commented on identity-verification/module_3/3.2 Improving accuracy using user vectors.ipynb
> +    "    print('Creating collection:' + collection_id)\n",
Removing redundant comment.
```suggestion
    "    print('Creating collection:' + collection_id)\n",
```

2023-08-07 14:04 UTC, matteofigus commented on identity-verification/module_3/3.2 Improving accuracy using user vectors.ipynb
> +  },
```suggestion
  {
   "cell_type": "markdown",
   "id": "958fc431-f505-4c15-942b-b4d3894a6dc8",
   "metadata": {},
   "source": [
    "### Confirm your collection creation\n",
    "Let's display the collections in our account to verify the previous collection was completed correctly."
   ]
  },
```

Should we merge these two cells?

2023-08-07 14:04 UTC, matteofigus commented on identity-verification/module_3/3.2 Improving accuracy using user vectors.ipynb
> +    "    while done==False:\n",
```suggestion
    "    while not done:\n",
```
nit: This reads more pythonic

2023-08-07 14:04 UTC, matteofigus commented on identity-verification/module_3/3.2 Improving accuracy using user vectors.ipynb
> +    "Once the collection is created, we can proceed to create a user. We are going to use the **create_user** method, which creates a new user in a collection and returns a unique user ID."
```suggestion
    "### Create a new user\n",
    "Once the collection is created, we can proceed to create a user. We are going to use the **create_user** method, which creates a new user in a collection and returns a unique user ID."
```

Should we merge these cells?

2023-08-07 14:04 UTC, matteofigus commented on identity-verification/module_3/3.2 Improving accuracy using user vectors.ipynb
> +   "source": [
```suggestion
    "user2_id = \"John\"\n",
```
Should we merge these cells?

2023-08-07 14:04 UTC, matteofigus commented on identity-verification/module_3/3.2 Improving accuracy using user vectors.ipynb
> +   "source": [
```suggestion
    "### Confirm your collection creation\n",
```

Should we merge these cells?

2023-08-07 14:04 UTC, matteofigus commented on identity-verification/module_3/3.2 Improving accuracy using user vectors.ipynb
> +   "source": [
```suggestion
    "### Add faces to a collection\n",
```

Should we merge these cells?

2023-08-07 14:04 UTC, matteofigus commented on identity-verification/module_3/3.2 Improving accuracy using user vectors.ipynb
> +   "source": [
```suggestion
    "### List faces in the collection\n",
```

Should we merge these cells?

2023-08-07 14:04 UTC, matteofigus commented on identity-verification/module_3/3.2 Improving accuracy using user vectors.ipynb
> +   "source": [
```suggestion
    "### Search face by image\n",
```

Should we merge these cells?

2023-08-07 14:04 UTC, matteofigus commented on identity-verification/module_3/3.2 Improving accuracy using user vectors.ipynb
> +    "print(\"The similarity seaarching against a single low quality image is: {}\".format(results[\"Similarity\"]))"
```suggestion
    "print(\"The similarity searching against a single low quality image is: {}\".format(results[\"Similarity\"]))"
```

2023-08-07 14:04 UTC, matteofigus commented on identity-verification/module_3/3.2 Improving accuracy using user vectors.ipynb
> +   "source": [
```suggestion
    "### Associate faces in the collections to a user\n",
```
Should we merge these cells?

2023-08-07 14:04 UTC, matteofigus commented on identity-verification/module_3/3.2 Improving accuracy using user vectors.ipynb
> +   "source": [
```suggestion
    "#### Associate a single face to a user\n",
```
Should we merge these cells?

2023-08-07 14:04 UTC, matteofigus commented on identity-verification/module_3/3.2 Improving accuracy using user vectors.ipynb
> +   "source": [
```suggestion
    "#### Associate multiple faces in the collections to a user\n",
```
Should we merge these cells?

2023-08-07 14:04 UTC, matteofigus commented on identity-verification/module_3/3.2 Improving accuracy using user vectors.ipynb
> +   "source": [
```suggestion
    "### Search Users by UserId or FaceId\n",
```
Should we merge these cells?

2023-08-07 14:04 UTC, matteofigus commented on identity-verification/module_3/3.2 Improving accuracy using user vectors.ipynb
> +   "source": [
```suggestion
    "### Search Users by Image\n",
```
Should we merge these cells?

2023-08-07 14:04 UTC, matteofigus commented on identity-verification/module_3/3.2 Improving accuracy using user vectors.ipynb
> +   "source": [
```suggestion
    "### Disassociate faces from a user\n",
```
Should we merge these cells?

2023-08-07 14:04 UTC, matteofigus commented on identity-verification/module_3/3.2 Improving accuracy using user vectors.ipynb
> +   "source": [
```suggestion
    "### Delete a user\n",
```
Should we merge these cells?

2023-08-07 14:04 UTC, matteofigus commented on identity-verification/module_3/3.2 Improving accuracy using user vectors.ipynb
> +   "source": [
```suggestion
    "### Delete collection\n",
```
Should we merge these cells?

2023-08-09 07:24 UTC, DanyStinson commented on identity-verification/module_3/3.2 Improving accuracy using user vectors.ipynb
> +  "availableInstances": [
Correct, this is SM Studio, let's remove it.

2023-08-09 07:28 UTC, DanyStinson commented
Accepted changes

2023-08-09 15:49 UTC, matteofigus approved these changes

2023-08-10 11:37 UTC, ConnorKirk commented on identity-verification/module_3/3.2 Improving accuracy using user vectors.ipynb
> +    "#ListUsers - Lists the users in a collection.\n",
```suggestion
    "# ListUsers - Lists the users in a collection.\n",
```

2023-08-10 11:39 UTC, ConnorKirk approved these changes
Added one suggestion

2023-08-10 11:44 UTC, merged